"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os


def tree(src):
    """Collect data files from src directory, preserving structure relative to src."""
    data_files = []
    src_path = os.path.normpath(src)

    for root, dirs, files in os.walk(src_path):
        if files:
            # Calculate the relative path from 'src' directory
            rel_root = os.path.relpath(root, "src")
            file_paths = [os.path.join(root, f) for f in files]
            data_files.append((rel_root, file_paths))

    return data_files


APP = ["src/main.py"]
DATA_FILES = tree("src/assets")
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
